/* =========================================================
   SONORA data layer
   The library is REAL: it is read from audio/manifest.json,
   which is generated by `python .github/scripts/add_music.py` from the MP3
   files themselves (tags + embedded artwork).

   Runtime collections (ARTISTS / ALBUMS / PLAYLISTS)
   start empty and are filled by app.js once the
   manifest loads. Every accessor has a safe fallback so an
   empty or loading library can never crash a page.
   ========================================================= */
'use strict';
var IMG = window.IMG || {};

/* Filled at runtime from the manifest */
var ARTISTS = {};
var ALBUMS = [];
/* Auto-built from the real library (see rebuildPlaylists) */
var PLAYLISTS = [];

/* Safe fallbacks — never return undefined */
function artist(id) {
  var a = ARTISTS[id];
  if (a) return a;
  return { id: id || '', name: 'Unknown artist', g: '', loc: '', ac: '#D9A441', img: '', sim: [], bio: '' };
}
function album(id) {
  for (var i = 0; i < ALBUMS.length; i++) if (ALBUMS[i].id === id) return ALBUMS[i];
  return { id: '', t: 'No album', a: '', y: 0, g: '', img: IMG.ORB || '', desc: '', tracks: [] };
}
function trackRef(r) {
  var p = String(r || '').split(':');
  var al = album(p[0]);
  var i = +p[1] || 0;
  var tr = (al.tracks && al.tracks[i]) || { id: '', t: 'Unknown', d: '0:00' };
  return { al: al, i: i, id: tr.id || '', t: tr.t, d: tr.d };
}
function playlist(id) {
  for (var i = 0; i < PLAYLISTS.length; i++) if (PLAYLISTS[i].id === id) return PLAYLISTS[i];
  return { id: '', t: 'Playlist', d: '', cur: '', img: IMG.ORB || '', tracks: [] };
}
function durS(d) {
  var p = String(d || '0:00').split(':');
  return (+p[0] || 0) * 60 + (+p[1] || 0);
}

/* Real-world music history (facts, not site data) */
var HISTORY = [
  { y: '1960', g: ['Jazz', 'Soul', 'Rock'], t: 'The album', a: 'Music becomes a journey', m: 'The long-player changes listening' },
  { y: '1980', g: ['Synthpop', 'Hip-hop', 'New wave'], t: 'Synthesizers & samplers', a: 'Machines enter the band', m: 'The studio moves into a bedroom' },
  { y: '2000', g: ['Indie', 'Electroclash', 'R&B'], t: 'The MP3', a: 'Music becomes a file', m: 'Listening detaches from the object' },
  { y: '2020', g: ['Hyperpop', 'Ambient revival'], t: 'Spatial audio', a: 'Listening becomes a room again', m: 'The quiet returns to recordings' }
];
var TECH = [
  ['1948', 'Vinyl', 'The first format.'],
  ['1963', 'Cassette', 'Portable, personal, imperfect.'],
  ['1982', 'Compact Disc', 'Silence becomes digital zero.'],
  ['1995', 'MP3', 'The file.'],
  ['2010', 'Streaming', 'Access replaces ownership.'],
  ['2021', 'Spatial audio', 'The mix gains a room.']
];

/* Every playable reference in the library, as "albumId:index" */
function allRefs() {
  var out = [];
  for (var i = 0; i < ALBUMS.length; i++) {
    var al = ALBUMS[i];
    for (var j = 0; j < al.tracks.length; j++) out.push(al.id + ':' + j);
  }
  return out;
}

/* slug() mirrors the one in app.js (kept local to avoid a load-order dependency) */
function slug(s) {
  return String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'x';
}

/* Auto-playlists derived from the real library */
function rebuildPlaylists() {
  PLAYLISTS.length = 0;
  var refs = allRefs();
  if (!refs.length) return;
  PLAYLISTS.push({
    id: 'pl-all', t: 'EVERYTHING', d: 'The whole library, in order.',
    cur: 'SONORA', img: (ALBUMS[0] && ALBUMS[0].img) || IMG.ORB || '', tracks: refs.slice()
  });
  var byGenre = {};
  for (var i = 0; i < ALBUMS.length; i++) {
    var g = (ALBUMS[i].g || '').split('/')[0].trim().toLowerCase();
    if (!g) continue;
    var bucket = byGenre[g] = byGenre[g] || [];
    for (var j = 0; j < ALBUMS[i].tracks.length; j++) bucket.push(ALBUMS[i].id + ':' + j);
  }
  for (var k in byGenre) {
    if (byGenre[k].length < 2) continue;
    PLAYLISTS.push({
      id: 'pl-genre-' + slug(k), t: k.toUpperCase(), d: 'Everything tagged ' + k + '.',
      cur: 'SONORA', img: IMG.ORB || '', tracks: byGenre[k]
    });
  }
}

window.SONORA_DATA = {
  IMG: IMG, ARTISTS: ARTISTS, ALBUMS: ALBUMS, PLAYLISTS: PLAYLISTS,
  HISTORY: HISTORY, TECH: TECH
};
window.artist = artist; window.album = album; window.trackRef = trackRef;
window.durS = durS; window.playlist = playlist;
window.allRefs = allRefs;
window.rebuildPlaylists = rebuildPlaylists;
